#!/usr/bin/env python3
"""Broadcast a push notification for each card/entry newly added to one of
the tracked pages below.

Run by .github/workflows/notify.yml after a push to main. For each tracked
page, compares its items against the previous commit (HEAD~1); for every
item whose href is new, POSTs {title, body, url, topic} to the push Worker's
/broadcast, tagged with that page's topic. Bells live on secret.html (one per
card — see secret.html's card-bell buttons and bell.js) except for "index"
(index.html's own bell) and "blog" (blog/index.html's own bell, which is also
mirrored as a card-bell on secret.html so the two share one subscription).

secret.html itself carries no cards worth diffing anymore — its own page-wide
bell was retired in favor of these per-destination topics — so it's not in
PAGES.

Each page's cards use different markup (hand-rolled per section), so each
entry below carries its own extraction regex instead of one shared pattern.
A capture group set is either (href, title) or (href, title, desc); when
there's no natural description in the markup, `default_body` fills in a
generic notification body instead.

A blog card's "new" href may still 404 live if the post itself wasn't
committed alongside it (see assets/blog-availability.js) — the subscriber
just gets a link that resolves once the post is pushed.

Env:
  PUSH_WORKER_URL   e.g. https://mrinaliniisin-push.<sub>.workers.dev
  BROADCAST_SECRET  shared bearer token (matches the Worker secret)
  SITE_ORIGIN       optional, default https://mrinaliniisin.github.io
"""
import html
import json
import os
import re
import subprocess
import sys
import urllib.request

# href, title, desc — robust to whatever follows inside the card, and to
# extra classes alongside "desc" (blog cards keep just "desc", but this
# tolerates either). Shared by index.html and blog/index.html, whose cards
# both follow the same card-link/h2/desc convention.
CARD_RE = re.compile(
    r'<a class="card-link" href="([^"]+)"[^>]*></a>\s*'
    r'<h2>(.*?)</h2>\s*<div class="[^"]*\bdesc\b[^"]*">(.*?)</div>', re.S)

# commonplace/index.html: <a class="cpb-card" href="…" data-text="…"><h2>…</h2></a>
# No separate description — data-text is the full (long) factoid body, not
# fit for a push notification, so this page uses default_body instead.
COMMONPLACE_RE = re.compile(
    r'<a class="cpb-card" href="([^"]+)"[^>]*><h2>(.*?)</h2></a>', re.S)

# theo/listicles/index.html (generated by Theo): title in .card-name, an
# "Updated <date>" line in .card-meta makes a reasonable notification body.
# hrefs are relative to theo/listicles/, unlike every other tracked page.
LISTICLES_RE = re.compile(
    r'<a class="card" href="([^"]+)">\s*<div class="card-name">(.*?)</div>.*?'
    r'<div class="card-meta">(.*?)</div>', re.S)

# tv-plot-maps/index.html: only real `<a class="card">` entries are matched —
# not-yet-built maps are `<div class="card soon">` (no href), so they're
# invisible to this regex until they actually ship. hrefs are relative to
# tv-plot-maps/.
TVPLOTMAPS_RE = re.compile(
    r'<a class="card" href="([^"]+)">\s*<p class="eyebrow">.*?</p>\s*'
    r'<h2 class="title">(.*?)</h2>\s*<p class="blurb">(.*?)</p>', re.S)

PAGES = [
    {"path": "index.html", "topic": "index", "regex": CARD_RE},
    {"path": "blog/index.html", "topic": "blog", "regex": CARD_RE},
    {"path": "commonplace/index.html", "topic": "commonplace", "regex": COMMONPLACE_RE,
     "default_body": "New entry in the Commonplace Book"},
    {"path": "theo/listicles/index.html", "topic": "listicles", "regex": LISTICLES_RE,
     "href_prefix": "theo/listicles/"},
    {"path": "tv-plot-maps/index.html", "topic": "tvplotmaps", "regex": TVPLOTMAPS_RE,
     "href_prefix": "tv-plot-maps/", "default_body": "New interactive plot map is up"},
]


def normalize_href(href, prefix):
    if href.startswith("http") or href.startswith("/"):
        return href
    return "/" + (prefix or "") + href


def cards(src, page):
    out = {}
    clean = lambda s: html.unescape(re.sub(r"\s+", " ", s).strip())
    for m in page["regex"].findall(src or ""):
        href, title = m[0], m[1]
        desc = clean(m[2]) if len(m) > 2 else (page.get("default_body") or "")
        out[normalize_href(href, page.get("href_prefix"))] = (clean(title), desc)
    return out


def prev_version(path):
    r = subprocess.run(["git", "show", "HEAD~1:" + path],
                       capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else ""


def broadcast(worker, secret, origin, topic, href, title, desc):
    url = href if href.startswith("http") else origin + "/" + href.lstrip("/")
    payload = json.dumps({
        "title": "New on Mrinalini S: " + title,
        "body": desc, "url": url, "topic": topic,
    }).encode()
    req = urllib.request.Request(
        worker + "/broadcast", data=payload, method="POST",
        headers={"Content-Type": "application/json",
                 "Authorization": "Bearer " + secret,
                 # Cloudflare's edge 403s the default Python-urllib UA as a bot.
                 "User-Agent": "mrinaliniisin-notify/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        print("notified %r (%s) -> %s %s" % (title, topic, resp.status, resp.read().decode()))


def main():
    worker = os.environ["PUSH_WORKER_URL"].rstrip("/")
    secret = os.environ["BROADCAST_SECRET"]
    origin = os.environ.get("SITE_ORIGIN", "https://mrinaliniisin.github.io").rstrip("/")

    any_added = False
    for page in PAGES:
        path = page["path"]
        if not os.path.exists(path):
            continue
        new = cards(open(path, encoding="utf-8").read(), page)
        old = cards(prev_version(path), page)
        added = [h for h in new if h not in old]
        for href in added:
            any_added = True
            title, desc = new[href]
            try:
                broadcast(worker, secret, origin, page["topic"], href, title, desc)
            except Exception as e:
                print("FAILED to notify %r: %s" % (title, e), file=sys.stderr)
                sys.exit(1)

    if not any_added:
        print("No new cards; nothing to notify.")


if __name__ == "__main__":
    main()
